def readconfig(file):
    with open("etc/" + file, "r") as f:
        x = f.readlines()
        y = []
        for line in x:
            if line.startswith("#") or line.startswith("//") or line == "":
                continue
            else:
                y.append(line)
        return y

def writeconfig(file, config):
    with open("etc/" + file, "w") as f:
        f.write("# Autogenerated by writeconfig\n")
        for line in config:
            f.write(line + "\n")
        f.close()
    
def getvalue(config, key):
    keys = []
    vals = []
    for line in config:
        x = line.split("=")
        keys.append(x[0])
        vals.append(x[1])
    return vals[keys.index(key)].strip("\n")

def getkey(config, value):
    keys = []
    vals = []
    for line in config:
        x = line.split("=")
        keys.append(x[0])
        vals.append(x[1])
    return keys[vals.index(value)].strip("\n")

def setvalue(config, key, value):
    keys = []
    vals = []
    for line in config:
        x = line.split("=")
        keys.append(x[0])
        vals.append(x[1])
    try:
        vals[keys.index(key)] = value
    except ValueError:
        keys.append(key)
        vals[keys.index(key)] = value
    newconfig = []
    for z in keys:
        newconfig.append(z + "=" + vals[keys.index(z)])

    return newconfig